apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: hexatec-dep
spec:
  # 6 Pods should exist at all times.
  replicas: 6
  template:
    metadata:
      name: hexatec-pod
      labels:
        type: webserver
        # Apply this label to pods and default
        # the Deployment label selector to this value
        
    spec:
      containers:
      - name: hexatec-cont
        # Run this image
        image: rekikmahmoud/hexatec:1.0
  selector:
    matchLabels:
      type: webserver     